[debug]
port = 8000
ip = "0.0.0.0"

[release]
port = 8000
ip = "0.0.0.0"

[default.databases]
development = { url = "postgres://crypto_api:password@localhost/crypto_api" }
production = {url = "postgres://crypto_api:aDRS8HkCJEZIuzK@top2.nearest.of.crypto-api-db.internal:5432/crypto_api?sslmode=disable"}

